=== hmrc/api-architecture/early-designs/insolvent-vat-api-draft/public/api/conf/1.0/schemas/VatReturnDeclaration.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Insolvent Organisation VAT Submission",
  "description": "Insolvent Organisation VAT Submission",
  "type": "object",
  "properties": {
    "periodKey": {
      "description": "The ID code for the period that this obligation belongs to. The format is a string of four alphanumeric characters. Occasionally the format includes the # symbol.",
      "$ref": "#/definitions/periodKey"
    },
    "vatDueSales": {
      "description": "VAT due on sales and other outputs. This corresponds to box 1 on the VAT Return form. The value must be between -9999999999999.99 and 9999999999999.99.",
      "$ref": "#/definitions/monetaryPosNeg13"
    },
    "vatDueAcquisitions": {
      "description": "VAT due on acquisitions from other EC Member States. This corresponds to box 2 on the VAT Return form. The value must be between -9999999999999.99 and 9999999999999.99.",
      "$ref": "#/definitions/monetaryPosNeg13"
    },
    "totalVatDue": {
      "description": "Total VAT due (the sum of vatDueSales and vatDueAcquisitions). This corresponds to box 3 on the VAT Return form. The value must be between -9999999999999.99 and 9999999999999.99.",
      "$ref": "#/definitions/monetaryPosNeg13"
    },
    "vatReclaimedCurrPeriod": {
      "description": "VAT reclaimed on purchases and other inputs (including acquisitions from the EC). This corresponds to box 4 on the VAT Return form. The value must be between -9999999999999.99 and 9999999999999.99.",
      "$ref": "#/definitions/monetaryPosNeg13"
    },
    "netVatDue": {
      "description": "The difference between totalVatDue and vatReclaimedCurrPeriod. This corresponds to box 5 on the VAT Return form. The value must be between 0.00 and 99999999999.99",
      "$ref": "#/definitions/monetaryPos11"
    },
    "totalValueSalesExVAT": {
      "description": "Total value of sales and all other outputs excluding any VAT. This corresponds to box 6 on the VAT Return form. The value must be in pounds (no pence) between -9999999999999 and 9999999999999.",
      "$ref": "#/definitions/monetaryPosNegZeroDec13"
    },
    "totalValuePurchasesExVAT": {
      "description": "Total value of purchases and all other inputs excluding any VAT (including exempt purchases). This corresponds to box 7 on the VAT Return form. The value must be in pounds (no pence) between -9999999999999 and 9999999999999.",
      "$ref": "#/definitions/monetaryPosNegZeroDec13"
    },
    "totalValueGoodsSuppliedExVAT": {
      "description": "Total value of all supplies of goods and related costs, excluding any VAT, to other EC member states. This corresponds to box 8 on the VAT Return form. The value must be between -9999999999999 and 9999999999999.",
      "$ref": "#/definitions/monetaryPosNegZeroDec13"
    },
    "totalAcquisitionsExVAT": {
      "description": "Total value of acquisitions of goods and related costs excluding any VAT, from other EC member states. This corresponds to box 9 on the VAT Return form. The value must be between -9999999999999 and 9999999999999.",
      "$ref": "#/definitions/monetaryPosNegZeroDec13"
    },
    "receivedAt": {
      "title": "The date & time the return was received",
      "description": "The date & time the return was received. UTC timezone",
      "type": "string",
      "format": "date-time"
    },
    "uniqueId": {
      "description": "A unique scan reference ID must be provided for an externally scanned submission.",
      "$ref": "#/definitions/uniqueId"
    }
  },
  "required": [
    "periodKey",
    "vatDueSales",
    "vatDueAcquisitions",
    "totalVatDue",
    "vatReclaimedCurrPeriod",
    "netVatDue",
    "totalValueSalesExVAT",
    "totalValuePurchasesExVAT",
    "totalValueGoodsSuppliedExVAT",
    "totalAcquisitionsExVAT",
    "receivedAt",
    "uniqueId"
  ],
  "definitions":
  {
    "periodKey": {
      "description": "The ID code for the period that this obligation belongs to. The format is a string of four alphanumeric characters. Occasionally the format includes the # symbol.",
      "type": "string",
      "pattern": "^[0-9]{2}[A-Z][A-Z0-9]$)|(^#[0-9]{3}$)|(^[0-9]{4}$"
    },
    "monetaryPos11": {
      "description": "Defines a monetary value (to 2 decimal places), between 0 and 99,999,999,999.99",
      "type": "number",
      "minimum": 0.0,
      "maximum": 99999999999.99,
      "multipleOf": 0.01
    },
    "monetaryPosNeg13": {
      "description": "Defines a monetary value (to 2 decimal places), between -9,999,999,999,999.99 and 9,999,999,999,999.99",
      "type": "number",
      "minimum": -9999999999999.99,
      "maximum": 9999999999999.99,
      "multipleOf": 0.01
    },
    "monetaryPosNegZeroDec13": {
      "description": "Defines a monetary value (to 2 zeroed decimal places), between -9,999,999,999,999.00 and 9,999,999,999,999.00",
      "type": "number",
      "minimum": -9999999999999.00,
      "maximum": 9999999999999.00,
      "multipleOf": 1.00
    },
    "uniqueId": {
      "description": "A unique scan reference ID must be provided for an externally scanned submission.",
      "type": "string",
      "pattern": "[A-Za-z0-9 \\-,.&'\\/()!]{1,10}$"
    }
  },
  "additionalProperties": false
}

=== hmrc/api-architecture/early-designs/insolvent-vat-api-draft/public/api/conf/1.0/examples/SubmitVatReturn.json
{
  "periodKey": "20A2",
  "vatDueSales": 105.50,
  "vatDueAcquisitions": -100.45,
  "totalVatDue": 5.05,
  "vatReclaimedCurrPeriod": 105.15,
  "netVatDue": 100.10,
  "totalValueSalesExVAT": 300,
  "totalValuePurchasesExVAT": 300,
  "totalValueGoodsSuppliedExVAT": 3000,
  "totalAcquisitionsExVAT": 3000,
  "receivedAt": "2017-01-01T00:01:00Z",
  "uniqueId": "a2-b3.cd5e"
}
